version: '2'
services:
  db:
    image: postgres:10.3
    environment:
      POSTGRES_DB: drupaldb
      POSTGRES_USER: drupaluser
      POSTGRES_PASSWORD: drupalpassword
    volumes:
      - db_data:/var/lib/postgresql
    restart: always
  drupal:
    depends_on:
      - db
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    restart: always
volumes:
  db_data:
